# Generated by Django 5.0.2 on 2024-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='travel_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='travel_preferences',
            field=models.TextField(blank=True),
        ),
    ]
