# Generated by Django 5.0.2 on 2024-09-19 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('travel_dates', models.DateField()),
                ('users_interested', models.ManyToManyField(blank=True, related_name='destination_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
